# Generated by Django 6.0.3 on 2026-04-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergame',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usergame',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
