import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  auth,
  dashboard,
}: {
  children: React.ReactNode;
  auth: React.ReactNode;
  dashboard: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {auth}
        {dashboard}
        {children}

        <Toaster
          position="bottom-right"
          theme="dark"
          toastOptions={{
            className: "border border-white/10 backdrop-blur-xl",
            style: {
              background: "rgba(20,20,35,0.65)",
              color: "white",
            },
          }}
        />
      </body>
    </html>
  );
}

